# Cross.toml

# Windows (64-bit)
[target.x86_64-pc-windows-gnu]
image = "rustembedded/cross:x86_64-pc-windows-gnu"

# macOS (64-bit)
[target.x86_64-apple-darwin]
image = "rustembedded/cross:x86_64-apple-darwin"
# You might need to mount the OSX SDK when cross-compiling for macOS.
osx_sdk_version = "10.14"

# Linux (64-bit)
[target.x86_64-unknown-linux-gnu]
image = "rustembedded/cross:x86_64-unknown-linux-gnu"

