[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["+nightly", "fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
# dependencies = ["clean"]

[tasks.release]
command = "cargo"
args = ["build", "--release"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.archive-win]
dependencies = ["release"]
script = '''
powershell $date = Get-Date -Format "yy.MM.dd"; New-Item -ItemType Directory -Force -Path "./$date-$($env:CARGO_MAKE_CRATE_NAME)-$($env:CARGO_MAKE_CRATE_VERSION)";
powershell $date = Get-Date -Format "yy.MM.dd"; Compress-Archive -Path "./target/release/$($env:CARGO_MAKE_CRATE_NAME).exe" -Force -DestinationPath "./$date-$($env:CARGO_MAKE_CRATE_NAME)-$($env:CARGO_MAKE_CRATE_VERSION)/$($env:CARGO_MAKE_CRATE_NAME).zip"
'''
