use crossterm::event::KeyEvent;

use crate::components::app::Mode as HomeMode;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Action {
    Close,
    EnterInsert,
    EnterNormal,
    MoveSelectionBottom,
    MoveSelectionEnd,
    MoveSelectionHome,
    MoveSelectionNext,
    MoveSelectionPrevious,
    MoveSelectionTop,
    MoveSelectionRight,
    MoveSelectionLeft,
    Pause(HomeMode),
    Quit,
    Init,
    SubmitSelection,
    Tick,
    Render,
    Resume,
    EnterSubset,
    UnPause,
    Refresh,
    NextAxis(usize),
    PreviousAxis(usize),
    IncrementAxis(usize),
    DecrementAxis(usize),
    Resize { x: u16, y: u16 },
    Suspend,
    SwitchModeToViewer(usize),
    SwitchModeToPicker,
    SwitchModeToHelp,
    SwitchModeToPreviousMode,
    ToggleLogger,
    ToggleTree,
    ToggleSelection,
    ToggleAllSelection,
    ToggleFormattedData,
    ViewerSliceRefresh,
    ReloadData,
}
