name: CD

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            file: target/release/e2020-data-viewer
            args: --best --lzma
            strip: true
          - os: windows-latest
            file: target/release/e2020-data-viewer.exe
            args: -9
            strip: false
          - os: macos-latest
            file: target/release/e2020-data-viewer
            args: --best
            strip: true

    steps:
      - uses: actions/checkout@v4

      - name: Get the release version from the tag
        shell: bash
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: |
          cargo build --verbose --release

      - name: Compress binaries
        uses: svenstaro/upx-action@v2
        with:
          files: ${{ matrix.file }}
          args: ${{ matrix.args }}
          strip: ${{ matrix.strip }}

      - name: Build archive
        shell: bash
        run: |
          dirname="e2020-data-viewer-${{ env.VERSION }}-${{ matrix.os }}"
          mkdir "$dirname"
          cp ${{ matrix.file }} "$dirname"
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            7z a "$dirname.zip" "$dirname"
            echo "ASSET=$dirname.zip" >> $GITHUB_ENV
          else
            tar -czvf "$dirname.tar.gz" "$dirname"
            echo "ASSET=$dirname.tar.gz" >> $GITHUB_ENV
          fi

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.ASSET }}
