name: CD

permissions:
  contents: write

on:
  release:
    types: [published]
  push:
    tags:
      - v[0-9]+.*

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            file: target/release/e2020-data-viewer
            args: --best --lzma
            strip: true
          - os: windows-latest
            file: target/release/e2020-data-viewer.exe
            args: -9
            strip: false
          - os: macos-latest
            file: target/release/e2020-data-viewer
            args: --best
            strip: true

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - name: Cache Cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache Cargo target
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-target-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: |
          cargo build --verbose --release

      - name: Compress binaries
        uses: svenstaro/upx-action@v2
        with:
          files: ${{ matrix.file }}
          args: ${{ matrix.args }}
          strip: ${{ matrix.strip }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: e2020-data-viewer-${{ matrix.os }}
          path: ${{ matrix.file }}


  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download all artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Create Release and Upload Artifacts
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ./artifacts/**/*.zip
            ./artifacts/**/*.tar.gz
